# Generated by Django 2.2.13 on 2022-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('music_choice', models.IntegerField()),
                ('food_choice', models.IntegerField()),
                ('decor_choice', models.IntegerField()),
                ('light_choice', models.IntegerField()),
                ('stage_choice', models.IntegerField()),
            ],
        ),
    ]
