# Generated by Django 2.2.13 on 2022-07-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='decor_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='light_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='music_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='stage_choice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
