# Generated by Django 2.2.13 on 2022-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220731_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='decor_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='food_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='light_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='music_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='stage_choice',
            field=models.IntegerField(default=0),
        ),
    ]
