# Generated by Django 2.2.13 on 2022-07-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220731_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
