# Generated by Django 2.2.13 on 2022-08-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220802_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=70)),
                ('mbl_no', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=70)),
                ('est_people', models.IntegerField()),
                ('venue', models.CharField(max_length=70)),
                ('venue_address', models.CharField(max_length=70)),
                ('venue_pin', models.CharField(max_length=70)),
                ('est_cost', models.IntegerField()),
                ('invite_image', models.URLField()),
            ],
        ),
    ]
