# Generated by Django 2.2.13 on 2022-08-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='venue_address',
            field=models.CharField(max_length=300),
        ),
    ]
