# Generated by Django 2.2.13 on 2022-08-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_mbl_no',
            field=models.CharField(max_length=60),
        ),
    ]
