# Generated by Django 2.2.13 on 2022-07-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='organiser/images')),
                ('desc', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
