# Generated by Django 2.2.13 on 2022-07-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0005_organiser_type_of_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('services', models.CharField(max_length=100)),
            ],
        ),
    ]
