# Generated by Django 2.2.13 on 2022-07-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0006_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['services']},
        ),
    ]
