# Generated by Django 2.2.13 on 2022-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0007_auto_20220730_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_image', models.ImageField(default='', upload_to='Event/images')),
                ('event_desc', models.TextField(default='', max_length=300)),
                ('category', models.ManyToManyField(to='organiser.Service')),
            ],
        ),
    ]
