# Generated by Django 2.2.13 on 2022-07-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0009_event_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='event_title',
        ),
    ]
