# Generated by Django 2.2.13 on 2022-07-30 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0010_auto_20220730_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='news_title',
        ),
    ]
