# Generated by Django 2.2.13 on 2022-07-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0011_auto_20220730_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_title', models.CharField(default='', max_length=50)),
                ('package_image', models.ImageField(default='', upload_to='Package/images')),
                ('package_desc', models.TextField(default='', max_length=300)),
                ('category', models.ManyToManyField(to='organiser.Service')),
            ],
        ),
    ]
