# Generated by Django 2.2.13 on 2022-07-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0012_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_price',
            field=models.IntegerField(default=10000),
        ),
    ]
