# Generated by Django 2.2.13 on 2022-08-08 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0016_auto_20220806_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='organiser',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='organiser/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 8, 8), null=True),
        ),
    ]
