# Generated by Django 2.2.13 on 2022-08-10 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0017_auto_20220808_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 8, 10), null=True),
        ),
    ]
