# Generated by Django 2.2.13 on 2022-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0019_auto_20220810_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('sub_name', models.CharField(max_length=30)),
            ],
        ),
    ]
