# Generated by Django 2.2.13 on 2022-08-10 15:17

from django.db import migrations, models
import organiser.models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0020_attend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attend',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, validators=[organiser.models.namevalidation]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=70, validators=[organiser.models.mblvalidation]),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='first_name',
            field=models.CharField(max_length=50, validators=[organiser.models.namevalidation]),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='last_name',
            field=models.CharField(max_length=50, validators=[organiser.models.namevalidation]),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='mobile_no',
            field=models.IntegerField(default=0, unique=True, validators=[organiser.models.mblvalidation]),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[organiser.models.usernamevalidation]),
        ),
    ]
